### PR TITLE
configure timeout

### PR DESCRIPTION
**Pull request by uchouhan**

### CODE REVIEW

**Comment by tim-schilling** [comment]
I think that's an easy merge if there's an environment variable and docs for it.

**Comment by uchouhan** [comment]
sounds good, I'll add a variable with docs and reopen!

**Comment by tim-schilling** [comment]
@uchouhan there are significant changes in this PR now. More than I expected for exposing a single parameter through an environment variable. Were the commits from yesterday intentional?

**Comment by uchouhan** [comment]
> @uchouhan there are significant changes in this PR now. More than I expected for exposing a single parameter through an environment variable. Were the commits from yesterday intentional?

hmm not sure how that happened, our repos have diverged quite a bit so may not make sense to merge unless you have the same use case and functionally its compatible, I'll close this PR otherwise

**Comment by tim-schilling** [comment]
At this time I don't have the availability to merge some of those changes upstream because I'd have to pull them out. I appreciate the thought though!

**Pull request closed without merging**
