### PR TITLE
remove proxychains SUN-398

### PR DESCRIPTION
**Pull request by uchouhan**

### CODE REVIEW

**Comment by tim-schilling** [comment]
Oh, that looks pretty clean! I may have to backport that to this repo.

**Comment by uchouhan** [comment]
if you're interested I can open a PR, we realized we didn't need `proxychains` because the ruby socket library does not use it, and also we don't want to proxy all TCP/HTTP requests, so doing that when needed in the application makes sense

also, the magicdns resolution issue is a `tailscale` bug, opened an issue here https://github.com/tailscale/tailscale/issues/10860

**Comment by tim-schilling** [comment]
I need to see if this will work for proxying the connections to postgres via psycopg. I'd rather not waste your time on a PR review. Having yours as a resource is sufficient for the time, but I wanted to acknowledge your approach.

**Comment by uchouhan** [comment]
gotcha, thanks, perhaps the `proxychains` installation can be a conditional too, happy to revert to using this repo if we can remove the dependency on `ALL_PROXY` and `proxychains`

**Comment by tim-schilling** [comment]
Good to know!

**Comment by bradymholt** [comment]
@uchouhan - 

> we realized we didn't need proxychains because the ruby socket library does not use it

It sounds like you are using a Ruby project.  Are you using the https://github.com/astro/socksify-ruby Gem for proxying connections, perhaps?  Also, are you connecting to a database via ActiveRecord over a Tailscale network with your modifications?

**Pull request closed without merging**
